### PR TITLE
Updated privacy files

### PR DESCRIPTION
**Pull request by AdilIqbal95**
Added provider.php and updated qformat_hotpot.php as privacy behat tests were failing.

### CODE REVIEW

**Comment by lucaboesch** [comment]
The string says "The Calendar block only displays existing calendar data." which isn't the right thing to say for question type hotpot.
Also, be sure to have a newline at the end of the php file.

**Comment by aspark21** [comment]
Nudge nudge :)

**Comment by gbateson** [comment]
Thanks very much aspark21 and lucaboesch, for your contributions and help in keeping the qformat_hotpot current.
Kind regards,
Gordon

**Comment by gbateson** [comment]
I have committed the changes to the public release of this plugin and made the new version available on Moodle.org too.
https://moodle.org/plugins/qformat_hotpot/

**Pull request merged**
