### PR TITLE
adding composer.json

### PR DESCRIPTION
**Pull request by danielneis**
Hello,

this adds a composer.json file so people can deploy the plugin using composer (getcomposer.org)

Hope you like.

Kind regards,
Daniel

### CODE REVIEW

**Comment by gbateson** [comment]
Hi, thanks for the offer of help but I don't think we need this composer file because Moodle has its own version dependency system. Gordon

**Comment by danielneis** [comment]
Hello, Gordon

this composer file (and the composer tool) are intended to do other type of dependency use cases than the Moodle's own system.
The Moodle's dependencies systems checks for dependencies at plugin install/update times and guarantees that you cannot install a plugin without other plugins it dependes on.
The Composer dependencies system let you create a file on you Moodle's root folder (actually, Moodle already have one, for phpunit and other developer tools) and list what plugins you want installed and do "php composer.php update" to have them all downloaded to the right folders from the right places, repositories and branches. This way, you can replicate a Moodle environment with all it's plugins with just a command. You can read more about this here: https://getcomposer.org/doc/00-intro.md

Kind regards,
Daniel

**Comment by gbateson** [comment]
If people want to create a Moodle site using the command line they have the "moosh" tool. I don't see the need for another dependency system, and I don't see the need to include the composer file in either HotPot module or the HotPot question import. The page you linked to is vague and abstract and does not help me understand in concrete terms how anyone would use composer with Moodle, nor does it explain the advantages of doing that rather than using Moodle's own versioning system or "moosh".

**Comment by danielneis** [comment]
Hello,

let me explain one use case:
- I work on an institution that have 4 different Moodle installs, because they have support to classic "classroom teaching", they have two different e-learning programs for different government institutions and the fourth one is a sandbox/test/develop-content installation
- In this project, there are 6 programmers
- If anyone of us want to replicate an environment with it's plugins in correct versions we cannot do this using moosh or other moodle default tools
- One way of doing this is having a composer.json file like this:
  
  {
      "repositories" : [
      {
          "type": "vcs",
          "url": "https://github.com/moodlehq/moodle-behat-extension"
      },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-block_attendance.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-filter_jmol.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-local_mobile.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-assignsubmission_onlineaudio.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-mod_attendance.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-mod_bigbluebuttonbn.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-mod_groupselect.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-mod_hotpot.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-mod_questionnaire.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-mod_scheduler.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-mod_vpl.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-qformat_hotpot.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-webservice_soapfda.git" },
      { "type": "vcs", "url": "https://github.com/danielneis/moodle-tool_editrolesbycap.git" }
      ],
      "require" : {
          "composer/installers" : "dev-master",
          "danmarsden/moodle-block_attendance" : "dev-composer",
          "geoffrowland/moodle-filter_jmol" : "dev-composer",
          "jleyva/moodle-local_mobile" : "dev-composer",
          "pauln/moodle-assignsubmission_onlineaudio" : "dev-composer",
          "danmarsden/moodle-mod_attendance" : "dev-composer",
          "blindsidenetworks/moodle-mod_bigbluebuttonbn" : "dev-composer",
          "skodak/moodle-mod_groupselect" : "dev-composer",
          "gbateson/moodle-mod_hotpot" : "dev-composer",
          "remotelearner/moodle-mod_questionnaire" : "dev-composer",
          "bostelm/moodle-mod_scheduler" : "dev-composer",
          "jcrodriguez-dis/moodle-mod_vpl" : "dev-composer",
          "gbateson/moodle-qformat_hotpot" : "dev-composer",
          "ghigio/moodle-webservice_soapfda" : "dev-composer",
          "moodleou/moodle-tool_editrolesbycap" : "dev-composer"
      },
      "require-dev": {
          "phpunit/phpunit": "3.7._",
          "phpunit/dbUnit": "1.2._",
          "moodlehq/behat-extension": "1.28.7"
      }
  }

https://github.com/danielneis/moodle/blob/COMPOSER_EXAMPLE/composer.json

And then you can clone the repository and then do "php composer.php update" and have all set up.
If the packages were also added to the http://packagist.org/ repository, the lines that specifies the repositories may be ommited.

Isn't this useful? =)

Kind regards,
Daniel

**Comment by gbateson** [comment]
Hi DanielNeis,
a long time has passed since your submitted your Pull request for the qformat_hotpot plugin for Moodle. Sorry about the delay, but thanks for your contribution. It has been included in the public download now.

Kind regards,
Gordon BATESON

**Pull request merged**
